name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use the appropriate version
      - name: Deploy to Server
        uses: appleboy/ssh-action@main
        #uses: appleboy/ssh-action@v2  # Use the appropriate version
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/hospitalMSLLLL
            /var/www/hospitalMSLLLL/.scripts/deploy.sh

