name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
            /usr/bin/ssh -vvv saiqa@192.168.58.130 'cd /var/www/hospitalMSLLLL && /var/www/hospitalMSLLLL/.script/deploy.sh'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}

