name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh-key
          chmod 600 ssh-key
          eval $(ssh-agent -s)
          ssh-add ./ssh-key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}

      - name: Deploy to Server
        run: |
          ssh saiqa@192.168.58.130 'cd /var/www/hospitalMSLLLL && /var/www/hospitalMSLLLL/.script/deploy.sh'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}

